name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          branch: gh-pages
          folder: docs/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
